#include <po_hi_gqueue.h>
#include <deployment.h>
#include <po_hi_types.h>
#include <request.h>
#include <types.h>
#include "subprograms.h"
#include <activity.h>
#include <po_hi_task.h>
#include <po_hi_main.h>
#include <po_hi_transport.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
__po_hi_port_t __po_hi_plant_outputfeedback_local_destinations[1] = {controller_global_outputfeedback};
__po_hi_uint8_t __po_hi_plant_woffsets[__po_hi_plant_nb_ports];
__po_hi_uint8_t __po_hi_plant_offsets[__po_hi_plant_nb_ports];
__po_hi_uint8_t __po_hi_plant_used_size[__po_hi_plant_nb_ports];
__po_hi_uint8_t __po_hi_plant_empties[__po_hi_plant_nb_ports];
__po_hi_uint8_t __po_hi_plant_first[__po_hi_plant_nb_ports];
__po_hi_request_t __po_hi_plant_recent[__po_hi_plant_nb_ports];
__po_hi_port_t __po_hi_plant_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_plant_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_plant_history[0];
__po_hi_uint8_t __po_hi_plant_n_dest[__po_hi_plant_nb_ports] = {0,1};
__po_hi_int8_t __po_hi_plant_fifo_size[__po_hi_plant_nb_ports] = {__PO_HI_GQUEUE_FIFO_INDATA,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_plant_destinations[__po_hi_plant_nb_ports] = {NULL,__po_hi_plant_outputfeedback_local_destinations};

/*!
 * \fn void plant_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task plant
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (plant_deliver) stores the incoming request for the taskplant
 */
void plant_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case plant_global_controllerinput:
    {
      __po_hi_gqueue_store_in (sunseekerplant_plant_k, plant_local_controllerinput, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* plant_job (void)
 * \brief Function executed by the task plant
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : Plant*/
/*  Get the IN ports values*/
void* plant_job (void)
{
  __po_hi_request_t static controllerinput_request;
  beacon_standard__single_float outputfeedback_request_var;
  __po_hi_request_t outputfeedback_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (sunseekerplant_plant_k, __po_hi_plant_nb_ports, __po_hi_plant_queue, __po_hi_plant_fifo_size, __po_hi_plant_first, __po_hi_plant_offsets, __po_hi_plant_woffsets, __po_hi_plant_n_dest, __po_hi_plant_destinations, __po_hi_plant_used_size, __po_hi_plant_history, __po_hi_plant_recent, __po_hi_plant_empties, __po_hi_plant_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (sunseekerplant_plant_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (sunseekerplant_plant_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (sunseekerplant_plant_k, plant_local_controllerinput))
    {
          __po_hi_gqueue_get_value (sunseekerplant_plant_k, plant_local_controllerinput, &(controllerinput_request));
      __po_hi_gqueue_next_value (sunseekerplant_plant_k, plant_local_controllerinput);

    }
    /*  Call implementation*/
    sunseeker__sunseekerplant_subprogram_beacon (controllerinput_request.vars.plant_global_controllerinput.plant_global_controllerinput, &(outputfeedback_request_var));
    /*  Set the OUT port values*/
    outputfeedback_request.vars.plant_global_outputfeedback.plant_global_outputfeedback = outputfeedback_request_var;
    outputfeedback_request.port = plant_global_outputfeedback;
    __po_hi_gqueue_store_out (sunseekerplant_plant_k, plant_local_outputfeedback, &(outputfeedback_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (sunseekerplant_plant_k, plant_global_outputfeedback);
    __po_hi_wait_for_next_period (sunseekerplant_plant_k);
  }
}


/*!
 * \fn void __po_hi_main_deliver (__po_hi_request_t* request)
 * \brief Used to deliver request to the appropriate ports
 *
 * This function takes a request as argument (\arg request) and calls the 
 * appropriate function for its delivery.To specify which function should be 
 * called, it extracts the receiver entity using the destination port.
 */
void __po_hi_main_deliver 
    (__po_hi_request_t* request)
{
  __po_hi_entity_t entity;

  entity = __po_hi_get_entity_from_global_port (request->port);
  switch (entity)
  {
    case sunseekerplant_plant_k_entity:
    {
      plant_deliver (request);

      break;
    }
    default:
    {
      break;
    }
  }
}


